import { StyleSheet } from 'react-native';
import { BRAND } from '@ride-app/shared';

/** Paleta Movify — alineada con packages/web-shared/styles.css */
export const colors = {
  primary: BRAND.colors.primary,
  primaryHover: '#bef264',
  primaryOnDark: BRAND.colors.primaryOnDark,
  primaryDim: 'rgba(163, 230, 53, 0.15)',
  bg: BRAND.colors.background,
  surface: '#0a0a0a',
  surfaceRaised: BRAND.colors.surface,
  border: '#1f1f1f',
  borderStrong: '#2a2a2a',
  text: '#ffffff',
  textMuted: '#a3a3a3',
  textDim: '#737373',
  danger: '#ff8f8f',
  mapRoute: BRAND.colors.primary,
  mapDriver: BRAND.colors.primary,
  mapPickup: '#ffffff',
} as const;

export const placeholderColor = colors.textDim;

export const appStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center' },
  container: { flex: 1, backgroundColor: colors.bg },
  authScroll: { padding: 24, paddingTop: 32, gap: 12 },
  authLogo: { width: 72, height: 72, borderRadius: 16, alignSelf: 'center', marginBottom: 4 },
  brandName: { color: colors.text, fontSize: 34, fontWeight: '800', textAlign: 'center', letterSpacing: -0.5 },
  brandNameAccent: { color: colors.primary },
  tagline: { color: colors.textMuted, textAlign: 'center', marginBottom: 8, fontSize: 15 },
  connectionOk: { color: colors.primary, textAlign: 'center', fontSize: 13, fontWeight: '600' },
  connectionBad: { color: colors.danger, textAlign: 'center', fontSize: 13 },
  link: { color: colors.primary, textAlign: 'center', marginBottom: 8, fontWeight: '500' },
  settingsBox: { gap: 8, marginBottom: 8 },
  input: {
    backgroundColor: colors.surface,
    color: colors.text,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    fontSize: 16,
  },
  btn: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  btnSmall: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    padding: 12,
    alignItems: 'center',
    flex: 1,
  },
  btnDisabled: { opacity: 0.45 },
  btnSecondary: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 999,
    padding: 14,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    flex: 1,
  },
  btnSecondaryText: { color: colors.text, fontWeight: '600' },
  btnText: { color: colors.primaryOnDark, fontWeight: '700', fontSize: 16 },
  error: { color: colors.danger },
  row: { flexDirection: 'row', gap: 8 },
  chip: {
    backgroundColor: colors.surfaceRaised,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    flex: 1,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: { color: colors.textMuted, textAlign: 'center', fontWeight: '500' },
  chipTextActive: { color: colors.primaryOnDark, fontWeight: '700', textAlign: 'center' },
  map: { flex: 1 },
  searchOverlay: { position: 'absolute', top: 0, left: 16, right: 16, zIndex: 20, gap: 8 },
  sheet: {
    backgroundColor: colors.surfaceRaised,
    padding: 16,
    borderTopWidth: 2,
    borderTopColor: colors.primary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '42%',
  },
  sheetHeader: { marginBottom: 10 },
  sheetTitle: { color: colors.text, fontSize: 20, fontWeight: '700' },
  roleBadge: { color: colors.primary, fontSize: 13, marginTop: 2, fontWeight: '600' },
  muted: { color: colors.textMuted, marginBottom: 8, fontSize: 14 },
  price: { color: colors.primary, fontSize: 22, fontWeight: '800', marginBottom: 8 },
  status: { color: colors.text, fontSize: 18, fontWeight: '600', marginBottom: 8 },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primaryDim,
    borderWidth: 1,
    borderColor: 'rgba(163, 230, 53, 0.3)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 8,
  },
  statusPillText: { color: colors.primary, fontWeight: '700', fontSize: 15 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  cardTitle: { color: colors.text, fontSize: 18, fontWeight: '700' },
  ratingBox: { gap: 6, marginTop: 8 },
  etaText: { color: colors.primary, fontWeight: '600', marginBottom: 4 },
});
