/** Delivery restaurant / fast-food catalog — ES, VE, IT. */

export type RestaurantCategory = 'fast_food' | 'restaurant';

export type DeliveryCountry = 'ES' | 'VE' | 'IT';

export interface DeliveryRestaurant {
  id: string;
  name: string;
  category: RestaurantCategory;
  cuisine: string;
  city: string;
  country: DeliveryCountry;
  address: string;
  lat: number;
  lng: number;
}

export const DELIVERY_COUNTRIES = ['ES', 'VE', 'IT'] as const;

export const DELIVERY_COUNTRY_META: Record<DeliveryCountry, { defaultCity: string; labelKey: string }> = {
  ES: { defaultCity: 'Madrid', labelKey: 'service.countryES' },
  VE: { defaultCity: 'Caracas', labelKey: 'service.countryVE' },
  IT: { defaultCity: 'Roma', labelKey: 'service.countryIT' },
};

export const SPAIN_CITIES = [
  'Madrid',
  'Barcelona',
  'Valencia',
  'Sevilla',
  'Málaga',
  'Bilbao',
  'Zaragoza',
] as const;

export const VENEZUELA_CITIES = [
  'Caracas',
  'Maracaibo',
  'Valencia',
  'Barquisimeto',
  'Maracay',
  'Mérida',
] as const;

export const ITALY_CITIES = [
  'Roma',
  'Milano',
  'Napoli',
  'Torino',
  'Firenze',
  'Bologna',
] as const;

export type SpainCity = (typeof SPAIN_CITIES)[number];
export type VenezuelaCity = (typeof VENEZUELA_CITIES)[number];
export type ItalyCity = (typeof ITALY_CITIES)[number];

/** Curated pickup points for food delivery (neighbourhood coords, illustrative branches). */
export const DELIVERY_RESTAURANTS: DeliveryRestaurant[] = [
  // —— Madrid ——
  {
    id: 'es-mad-mcd-sol',
    name: "McDonald's Sol",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Madrid',
    country: 'ES',
    address: 'Plaza de la Puerta del Sol 6, Madrid',
    lat: 40.4169,
    lng: -3.7035,
  },
  {
    id: 'es-mad-bk-granvia',
    name: 'Burger King Gran Vía',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Madrid',
    country: 'ES',
    address: 'Gran Vía 49, Madrid',
    lat: 40.4203,
    lng: -3.7058,
  },
  {
    id: 'es-mad-kfc-príncipe',
    name: 'KFC Príncipe Pío',
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Madrid',
    country: 'ES',
    address: 'Paseo de la Florida 2, Madrid',
    lat: 40.4211,
    lng: -3.7201,
  },
  {
    id: 'es-mad-telepizza-malasaña',
    name: 'Telepizza Malasaña',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Madrid',
    country: 'ES',
    address: 'Calle Fuencarral 45, Madrid',
    lat: 40.4241,
    lng: -3.7009,
  },
  {
    id: 'es-mad-dominos-latina',
    name: "Domino's Pizza Latina",
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Madrid',
    country: 'ES',
    address: 'Calle de la Princesa 25, Madrid',
    lat: 40.4272,
    lng: -3.7165,
  },
  {
    id: 'es-mad-goiko-chueca',
    name: 'Goiko Grill Chueca',
    category: 'restaurant',
    cuisine: 'burgers',
    city: 'Madrid',
    country: 'ES',
    address: 'Calle Hortaleza 49, Madrid',
    lat: 40.4248,
    lng: -3.6975,
  },
  {
    id: 'es-mad-100montaditos',
    name: '100 Montaditos Plaza Mayor',
    category: 'restaurant',
    cuisine: 'spanish',
    city: 'Madrid',
    country: 'ES',
    address: 'Plaza Mayor 1, Madrid',
    lat: 40.4155,
    lng: -3.7074,
  },
  {
    id: 'es-mad-vips-castellana',
    name: "Vips Castellana",
    category: 'restaurant',
    cuisine: 'casual',
    city: 'Madrid',
    country: 'ES',
    address: 'Paseo de la Castellana 89, Madrid',
    lat: 40.4475,
    lng: -3.6905,
  },
  {
    id: 'es-mad-fosters-azca',
    name: "Foster's Hollywood AZCA",
    category: 'restaurant',
    cuisine: 'american',
    city: 'Madrid',
    country: 'ES',
    address: 'Paseo de la Castellana 95, Madrid',
    lat: 40.4502,
    lng: -3.6912,
  },
  {
    id: 'es-mad-rodilla-atocha',
    name: 'Rodilla Atocha',
    category: 'fast_food',
    cuisine: 'sandwiches',
    city: 'Madrid',
    country: 'ES',
    address: 'Plaza del Emperador Carlos V, Madrid',
    lat: 40.4065,
    lng: -3.6915,
  },

  // —— Barcelona ——
  {
    id: 'es-bcn-mcd-rambla',
    name: "McDonald's La Rambla",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Barcelona',
    country: 'ES',
    address: 'La Rambla 115, Barcelona',
    lat: 41.3835,
    lng: 2.1734,
  },
  {
    id: 'es-bcn-bk-diagonal',
    name: 'Burger King Diagonal',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Barcelona',
    country: 'ES',
    address: 'Avinguda Diagonal 523, Barcelona',
    lat: 41.3947,
    lng: 2.1528,
  },
  {
    id: 'es-bcn-kfc-glories',
    name: 'KFC Glòries',
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Barcelona',
    country: 'ES',
    address: 'Avinguda Diagonal 208, Barcelona',
    lat: 41.4036,
    lng: 2.1914,
  },
  {
    id: 'es-bcn-telepizza-gracia',
    name: 'Telepizza Gràcia',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Barcelona',
    country: 'ES',
    address: 'Carrer Gran de Gràcia 78, Barcelona',
    lat: 41.4002,
    lng: 2.1575,
  },
  {
    id: 'es-bcn-tagliatella',
    name: 'La Tagliatella Born',
    category: 'restaurant',
    cuisine: 'italian',
    city: 'Barcelona',
    country: 'ES',
    address: 'Passeig del Born 16, Barcelona',
    lat: 41.3852,
    lng: 2.1833,
  },
  {
    id: 'es-bcn-goiko-eixample',
    name: 'Goiko Eixample',
    category: 'restaurant',
    cuisine: 'burgers',
    city: 'Barcelona',
    country: 'ES',
    address: 'Carrer de Provença 231, Barcelona',
    lat: 41.3931,
    lng: 2.1608,
  },
  {
    id: 'es-bcn-100montaditos',
    name: '100 Montaditos Barceloneta',
    category: 'restaurant',
    cuisine: 'spanish',
    city: 'Barcelona',
    country: 'ES',
    address: 'Passeig Joan de Borbó 42, Barcelona',
    lat: 41.3789,
    lng: 2.1895,
  },

  // —— Valencia ——
  {
    id: 'es-vlc-mcd-colon',
    name: "McDonald's Colón",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Valencia',
    country: 'ES',
    address: 'Calle de Colón 20, Valencia',
    lat: 39.4695,
    lng: -0.3712,
  },
  {
    id: 'es-vlc-bk-nuevo-centro',
    name: 'Burger King Nuevo Centro',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Valencia',
    country: 'ES',
    address: 'Avenida de Pius XII 2, Valencia',
    lat: 39.4812,
    lng: -0.3905,
  },
  {
    id: 'es-vlc-telepizza-ruzafa',
    name: 'Telepizza Ruzafa',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Valencia',
    country: 'ES',
    address: 'Calle de Cádiz 38, Valencia',
    lat: 39.4628,
    lng: -0.3725,
  },
  {
    id: 'es-vlc-100montaditos',
    name: '100 Montaditos Mercado Central',
    category: 'restaurant',
    cuisine: 'spanish',
    city: 'Valencia',
    country: 'ES',
    address: 'Plaza del Mercado, Valencia',
    lat: 39.4745,
    lng: -0.3788,
  },

  // —— Sevilla ——
  {
    id: 'es-sev-mcd-sierpes',
    name: "McDonald's Sierpes",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Sevilla',
    country: 'ES',
    address: 'Calle Sierpes 55, Sevilla',
    lat: 37.3891,
    lng: -5.9945,
  },
  {
    id: 'es-sev-bk-nervion',
    name: 'Burger King Nervión',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Sevilla',
    country: 'ES',
    address: 'Avenida Luis de Morales, Sevilla',
    lat: 37.3835,
    lng: -5.9728,
  },
  {
    id: 'es-sev-kfc-plaza',
    name: 'KFC Plaza de Armas',
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Sevilla',
    country: 'ES',
    address: 'Plaza de Armas, Sevilla',
    lat: 37.3918,
    lng: -6.0042,
  },
  {
    id: 'es-sev-tagliatella',
    name: 'La Tagliatella Triana',
    category: 'restaurant',
    cuisine: 'italian',
    city: 'Sevilla',
    country: 'ES',
    address: 'Calle Betis 12, Sevilla',
    lat: 37.3832,
    lng: -6.0025,
  },

  // —— Málaga ——
  {
    id: 'es-mlg-mcd-larios',
    name: "McDonald's Larios",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Málaga',
    country: 'ES',
    address: 'Calle Marqués de Larios 5, Málaga',
    lat: 36.7202,
    lng: -4.4214,
  },
  {
    id: 'es-mlg-bk-malagueta',
    name: 'Burger King Malagueta',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Málaga',
    country: 'ES',
    address: 'Paseo Marítimo Pablo Ruiz Picasso, Málaga',
    lat: 36.7165,
    lng: -4.4112,
  },
  {
    id: 'es-mlg-telepizza',
    name: 'Telepizza Centro',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Málaga',
    country: 'ES',
    address: 'Calle Granada 40, Málaga',
    lat: 36.7218,
    lng: -4.4185,
  },

  // —— Bilbao ——
  {
    id: 'es-bio-mcd-moyua',
    name: "McDonald's Moyúa",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Bilbao',
    country: 'ES',
    address: 'Plaza Federico Moyúa, Bilbao',
    lat: 43.2627,
    lng: -2.9350,
  },
  {
    id: 'es-bio-bk-indautxu',
    name: 'Burger King Indautxu',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Bilbao',
    country: 'ES',
    address: 'Plaza Indautxu, Bilbao',
    lat: 43.2605,
    lng: -2.9442,
  },
  {
    id: 'es-bio-100montaditos',
    name: '100 Montaditos Casco Viejo',
    category: 'restaurant',
    cuisine: 'spanish',
    city: 'Bilbao',
    country: 'ES',
    address: 'Calle del Correo 2, Bilbao',
    lat: 43.2575,
    lng: -2.9235,
  },

  // —— Zaragoza ——
  {
    id: 'es-zgz-mcd-paseo',
    name: "McDonald's Paseo Independencia",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Zaragoza',
    country: 'ES',
    address: 'Paseo de la Independencia 24, Zaragoza',
    lat: 41.6505,
    lng: -0.8805,
  },
  {
    id: 'es-zgz-bk-granvia',
    name: 'Burger King Gran Vía',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Zaragoza',
    country: 'ES',
    address: 'Avenida de César Augusto, Zaragoza',
    lat: 41.6542,
    lng: -0.8865,
  },
  {
    id: 'es-zgz-telepizza',
    name: 'Telepizza Delicias',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Zaragoza',
    country: 'ES',
    address: 'Avenida de Navarra 50, Zaragoza',
    lat: 41.6485,
    lng: -0.9102,
  },

  // —— Caracas ——
  {
    id: 've-ccs-mcd-chacao',
    name: "McDonald's Chacao",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Caracas',
    country: 'VE',
    address: 'Av. Francisco de Miranda, Chacao, Caracas',
    lat: 10.4955,
    lng: -66.8532,
  },
  {
    id: 've-ccs-bk-ccct',
    name: 'Burger King CCCT',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Caracas',
    country: 'VE',
    address: 'Centro Ciudad Comercial Tamanaco, Caracas',
    lat: 10.4885,
    lng: -66.8558,
  },
  {
    id: 've-ccs-wendys-altamira',
    name: "Wendy's Altamira",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Caracas',
    country: 'VE',
    address: 'Av. San Juan Bosco, Altamira, Caracas',
    lat: 10.4968,
    lng: -66.8495,
  },
  {
    id: 've-ccs-arturos-lasmercedes',
    name: "Arturo's Las Mercedes",
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Caracas',
    country: 'VE',
    address: 'Calle París, Las Mercedes, Caracas',
    lat: 10.4912,
    lng: -66.8585,
  },
  {
    id: 've-ccs-dominos-sabana',
    name: "Domino's Pizza Sabana Grande",
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Caracas',
    country: 'VE',
    address: 'Blvd. de Sabana Grande, Caracas',
    lat: 10.4925,
    lng: -66.8755,
  },
  {
    id: 've-ccs-pizzahut-chacao',
    name: 'Pizza Hut Chacao',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Caracas',
    country: 'VE',
    address: 'Av. Francisco de Miranda, Chacao, Caracas',
    lat: 10.4942,
    lng: -66.8518,
  },
  {
    id: 've-ccs-arepera-sambil',
    name: 'Arepera Sambil',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Caracas',
    country: 'VE',
    address: 'Centro Sambil Chacao, Caracas',
    lat: 10.4982,
    lng: -66.8538,
  },
  {
    id: 've-ccs-tropiburger',
    name: 'Tropi Burger Los Palos Grandes',
    category: 'restaurant',
    cuisine: 'burgers',
    city: 'Caracas',
    country: 'VE',
    address: 'Av. Andrés Bello, Los Palos Grandes, Caracas',
    lat: 10.4988,
    lng: -66.8465,
  },
  {
    id: 've-ccs-elbus',
    name: 'El Bus de Chamos Plaza Venezuela',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Caracas',
    country: 'VE',
    address: 'Plaza Venezuela, Caracas',
    lat: 10.495,
    lng: -66.898,
  },

  // —— Maracaibo ——
  {
    id: 've-mar-mcd-sambil',
    name: "McDonald's Sambil Maracaibo",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Maracaibo',
    country: 'VE',
    address: 'Sambil Maracaibo, Av. 17, Maracaibo',
    lat: 10.6665,
    lng: -71.6155,
  },
  {
    id: 've-mar-bk-bella-vista',
    name: 'Burger King Bella Vista',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Maracaibo',
    country: 'VE',
    address: 'Av. 15 Delicias, Bella Vista, Maracaibo',
    lat: 10.6725,
    lng: -71.6082,
  },
  {
    id: 've-mar-arturos',
    name: "Arturo's 5 de Julio",
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Maracaibo',
    country: 'VE',
    address: 'Av. 5 de Julio, Maracaibo',
    lat: 10.6688,
    lng: -71.6125,
  },
  {
    id: 've-mar-arepera',
    name: 'Arepera El Fogón del Zulia',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Maracaibo',
    country: 'VE',
    address: 'Calle 77, Maracaibo',
    lat: 10.6645,
    lng: -71.6185,
  },

  // —— Valencia (VE) ——
  {
    id: 've-val-mcd-sambil',
    name: "McDonald's Sambil Valencia",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Valencia',
    country: 'VE',
    address: 'Sambil Valencia, Av. Universitaria, Valencia',
    lat: 10.1655,
    lng: -68.0085,
  },
  {
    id: 've-val-bk-norte',
    name: 'Burger King Av. Bolívar Norte',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Valencia',
    country: 'VE',
    address: 'Av. Bolívar Norte, Valencia',
    lat: 10.1825,
    lng: -68.0025,
  },
  {
    id: 've-val-dominos',
    name: "Domino's Pizza Prebo",
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Valencia',
    country: 'VE',
    address: 'Centro Comercial Prebo, Valencia',
    lat: 10.1785,
    lng: -67.9985,
  },
  {
    id: 've-val-pollos',
    name: 'Pollos Mario Naguanagua',
    category: 'restaurant',
    cuisine: 'chicken',
    city: 'Valencia',
    country: 'VE',
    address: 'Av. Universidad, Naguanagua, Valencia',
    lat: 10.2155,
    lng: -68.0155,
  },

  // —— Barquisimeto ——
  {
    id: 've-brm-mcd',
    name: "McDonald's Barquisimeto",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Barquisimeto',
    country: 'VE',
    address: 'Av. Vargas, Barquisimeto',
    lat: 10.0675,
    lng: -69.3225,
  },
  {
    id: 've-brm-bk',
    name: 'Burger King Lara',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Barquisimeto',
    country: 'VE',
    address: 'CC Sambil Barquisimeto',
    lat: 10.0725,
    lng: -69.3155,
  },
  {
    id: 've-brm-arepera',
    name: 'Arepera El Criollo',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Barquisimeto',
    country: 'VE',
    address: 'Carrera 19, Barquisimeto',
    lat: 10.0645,
    lng: -69.3285,
  },

  // —— Maracay ——
  {
    id: 've-my-mcd',
    name: "McDonald's Maracay",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Maracay',
    country: 'VE',
    address: 'Av. Las Delicias, Maracay',
    lat: 10.2515,
    lng: -67.5955,
  },
  {
    id: 've-my-arturos',
    name: "Arturo's Maracay",
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Maracay',
    country: 'VE',
    address: 'Av. Constitución, Maracay',
    lat: 10.2465,
    lng: -67.6015,
  },
  {
    id: 've-my-arepera',
    name: 'Arepera La Aragüeña',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Maracay',
    country: 'VE',
    address: 'Av. Bermúdez, Maracay',
    lat: 10.2485,
    lng: -67.5985,
  },

  // —— Mérida ——
  {
    id: 've-mrd-mcd',
    name: "McDonald's Mérida",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Mérida',
    country: 'VE',
    address: 'Av. Las Américas, Mérida',
    lat: 8.5975,
    lng: -71.1445,
  },
  {
    id: 've-mrd-pizzahut',
    name: 'Pizza Hut Mérida',
    category: 'fast_food',
    cuisine: 'pizza',
    city: 'Mérida',
    country: 'VE',
    address: 'Av. Urdaneta, Mérida',
    lat: 8.5925,
    lng: -71.1525,
  },
  {
    id: 've-mrd-arepera',
    name: 'Arepera El Teleférico',
    category: 'restaurant',
    cuisine: 'venezuelan',
    city: 'Mérida',
    country: 'VE',
    address: 'Plaza Las Heroínas, Mérida',
    lat: 8.5895,
    lng: -71.1565,
  },

  // —— Roma ——
  {
    id: 'it-rom-mcd-termini',
    name: "McDonald's Termini",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Roma',
    country: 'IT',
    address: 'Piazza dei Cinquecento, Roma',
    lat: 41.9015,
    lng: 12.5008,
  },
  {
    id: 'it-rom-bk-piazza-venezia',
    name: 'Burger King Piazza Venezia',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Roma',
    country: 'IT',
    address: 'Via del Corso 181, Roma',
    lat: 41.8965,
    lng: 12.4825,
  },
  {
    id: 'it-rom-oldwildwest',
    name: 'Old Wild West Tiburtina',
    category: 'restaurant',
    cuisine: 'american',
    city: 'Roma',
    country: 'IT',
    address: 'Via Tiburtina 1113, Roma',
    lat: 41.9215,
    lng: 12.5485,
  },
  {
    id: 'it-rom-spontini',
    name: 'Pizzeria Spontini Prati',
    category: 'restaurant',
    cuisine: 'pizza',
    city: 'Roma',
    country: 'IT',
    address: 'Via Cola di Rienzo 50, Roma',
    lat: 41.9085,
    lng: 12.4625,
  },
  {
    id: 'it-rom-kfc',
    name: 'KFC Roma Est',
    category: 'fast_food',
    cuisine: 'chicken',
    city: 'Roma',
    country: 'IT',
    address: 'Via Prenestina 180, Roma',
    lat: 41.8925,
    lng: 12.5455,
  },

  // —— Milano ——
  {
    id: 'it-mil-mcd-duomo',
    name: "McDonald's Duomo",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Milano',
    country: 'IT',
    address: 'Piazza del Duomo, Milano',
    lat: 45.4642,
    lng: 9.1900,
  },
  {
    id: 'it-mil-bk-centrale',
    name: 'Burger King Stazione Centrale',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Milano',
    country: 'IT',
    address: 'Piazza Duca d\'Aosta, Milano',
    lat: 45.4865,
    lng: 9.2045,
  },
  {
    id: 'it-mil-roadhouse',
    name: 'Roadhouse Grill Porta Nuova',
    category: 'restaurant',
    cuisine: 'american',
    city: 'Milano',
    country: 'IT',
    address: 'Piazza Gae Aulenti, Milano',
    lat: 45.4835,
    lng: 9.1905,
  },
  {
    id: 'it-mil-pizzikotto',
    name: 'Pizzikotto Navigli',
    category: 'restaurant',
    cuisine: 'pizza',
    city: 'Milano',
    country: 'IT',
    address: 'Alzaia Naviglio Grande 20, Milano',
    lat: 45.4515,
    lng: 9.1725,
  },

  // —— Napoli ——
  {
    id: 'it-nap-mcd-garibaldi',
    name: "McDonald's Garibaldi",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Napoli',
    country: 'IT',
    address: 'Piazza Garibaldi, Napoli',
    lat: 40.8525,
    lng: 14.2685,
  },
  {
    id: 'it-nap-bk',
    name: 'Burger King Toledo',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Napoli',
    country: 'IT',
    address: 'Via Toledo 100, Napoli',
    lat: 40.8415,
    lng: 14.2485,
  },
  {
    id: 'it-nap-pizzeria',
    name: "L'Antica Pizzeria da Michele",
    category: 'restaurant',
    cuisine: 'pizza',
    city: 'Napoli',
    country: 'IT',
    address: 'Via Cesare Sersale 1, Napoli',
    lat: 40.8495,
    lng: 14.2635,
  },

  // —— Torino ——
  {
    id: 'it-tor-mcd',
    name: "McDonald's Porta Nuova",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Torino',
    country: 'IT',
    address: 'Corso Vittorio Emanuele II, Torino',
    lat: 45.0625,
    lng: 7.6785,
  },
  {
    id: 'it-tor-bk',
    name: 'Burger King Lingotto',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Torino',
    country: 'IT',
    address: 'Via Nizza 230, Torino',
    lat: 45.0325,
    lng: 7.6655,
  },
  {
    id: 'it-tor-oldwildwest',
    name: 'Old Wild West Torino',
    category: 'restaurant',
    cuisine: 'american',
    city: 'Torino',
    country: 'IT',
    address: 'Corso Francia 15, Torino',
    lat: 45.0755,
    lng: 7.6555,
  },

  // —— Firenze ——
  {
    id: 'it-fir-mcd',
    name: "McDonald's Firenze SMN",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Firenze',
    country: 'IT',
    address: 'Piazza della Stazione, Firenze',
    lat: 43.7765,
    lng: 11.2485,
  },
  {
    id: 'it-fir-bk',
    name: 'Burger King Duomo',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Firenze',
    country: 'IT',
    address: 'Via de\' Cerretani, Firenze',
    lat: 43.7735,
    lng: 11.2545,
  },
  {
    id: 'it-fir-pizzeria',
    name: 'Pizzeria Gusta Firenze',
    category: 'restaurant',
    cuisine: 'pizza',
    city: 'Firenze',
    country: 'IT',
    address: 'Via dei Neri 10, Firenze',
    lat: 43.7685,
    lng: 11.2585,
  },

  // —— Bologna ——
  {
    id: 'it-bol-mcd',
    name: "McDonald's Bologna Centrale",
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Bologna',
    country: 'IT',
    address: 'Piazza Medaglie d\'Oro, Bologna',
    lat: 44.5055,
    lng: 11.3425,
  },
  {
    id: 'it-bol-bk',
    name: 'Burger King Via Rizzoli',
    category: 'fast_food',
    cuisine: 'burgers',
    city: 'Bologna',
    country: 'IT',
    address: 'Via Rizzoli 5, Bologna',
    lat: 44.4945,
    lng: 11.3465,
  },
  {
    id: 'it-bol-trattoria',
    name: 'Trattoria da Gianni',
    category: 'restaurant',
    cuisine: 'italian',
    city: 'Bologna',
    country: 'IT',
    address: 'Via del Preti 8, Bologna',
    lat: 44.4925,
    lng: 11.3415,
  },
];

export interface RestaurantFilter {
  country?: DeliveryCountry | string;
  city?: string;
  category?: RestaurantCategory | 'all';
  q?: string;
}

export function listDeliveryRestaurants(filter: RestaurantFilter = {}): DeliveryRestaurant[] {
  const q = filter.q?.trim().toLowerCase();
  return DELIVERY_RESTAURANTS.filter((r) => {
    if (filter.country && r.country !== filter.country) return false;
    if (filter.city && r.city.toLowerCase() !== filter.city.toLowerCase()) return false;
    if (filter.category && filter.category !== 'all' && r.category !== filter.category) return false;
    if (q) {
      const hay = `${r.name} ${r.cuisine} ${r.city} ${r.address}`.toLowerCase();
      if (!hay.includes(q)) return false;
    }
    return true;
  });
}

export function getDeliveryRestaurant(id: string): DeliveryRestaurant | undefined {
  return DELIVERY_RESTAURANTS.find((r) => r.id === id);
}

export function deliveryCities(country: DeliveryCountry | string = 'ES'): string[] {
  const cities = new Set(
    DELIVERY_RESTAURANTS.filter((r) => r.country === country).map((r) => r.city),
  );
  const locale = country === 'IT' ? 'it' : 'es';
  return [...cities].sort((a, b) => a.localeCompare(b, locale));
}

export function isDeliveryCountry(code: string): code is DeliveryCountry {
  return (DELIVERY_COUNTRIES as readonly string[]).includes(code);
}
