tunnel: 55818726-7a1f-459c-a904-00f5487e6aad
credentials-file: /Users/server/.cloudflared/55818726-7a1f-459c-a904-00f5487e6aad.json
protocol: http2

ingress:
  - hostname: api.vescreenflow.com
    service: http://127.0.0.1:4000
  - hostname: movify-api.vescreenflow.com
    service: http://127.0.0.1:4001
  - hostname: movify.vescreenflow.com
    service: http://127.0.0.1:5174
  - hostname: movify-driver.vescreenflow.com
    service: http://127.0.0.1:5175
  - hostname: movify-admin.vescreenflow.com
    service: http://127.0.0.1:5176
  - service: http_status:404
